/// English short names for ISO 3166 country codes.
///
/// Spelled the way the config bot writes them into the pool -- "Czechia",
/// "South Korea", "United States" -- so a server from a user's own
/// subscription and one from Verna's pool read the same in the list. The bot's
/// 74 codes were read straight from its database; the rest are the countries
/// most likely to turn up in a share link beside them.
class CountryNames {
  const CountryNames._();

  /// The name for [code], or the code itself when it is not listed -- a code
  /// is still more useful on a row than nothing.
  static String of(String code) {
    final upper = code.toUpperCase();
    return _names[upper] ?? upper;
  }

  /// The Persian name, falling back to the English one and then to the code.
  ///
  /// A Persian speaker reading a list of exits should not have to parse
  /// "Netherlands" in the middle of a Persian sentence -- and a Latin word
  /// inside an RTL line is also the thing most likely to reorder on screen.
  static String persian(String code) {
    final upper = code.toUpperCase();
    return _persian[upper] ?? _names[upper] ?? upper;
  }

  static const Map<String, String> _persian = {
    'AD': 'آندورا',
    'AE': 'امارات',
    'AF': 'افغانستان',
    'AL': 'آلبانی',
    'AM': 'ارمنستان',
    'AR': 'آرژانتین',
    'AT': 'اتریش',
    'AU': 'استرالیا',
    'AZ': 'آذربایجان',
    'BA': 'بوسنی و هرزگوین',
    'BD': 'بنگلادش',
    'BE': 'بلژیک',
    'BG': 'بلغارستان',
    'BH': 'بحرین',
    'BO': 'بولیوی',
    'BR': 'برزیل',
    'BY': 'بلاروس',
    'BZ': 'بلیز',
    'CA': 'کانادا',
    'CH': 'سوئیس',
    'CL': 'شیلی',
    'CN': 'چین',
    'CO': 'کلمبیا',
    'CR': 'کاستاریکا',
    'CW': 'کوراسائو',
    'CY': 'قبرس',
    'CZ': 'چک',
    'DE': 'آلمان',
    'DK': 'دانمارک',
    'DO': 'دومینیکن',
    'DZ': 'الجزایر',
    'EC': 'اکوادور',
    'EE': 'استونی',
    'EG': 'مصر',
    'ES': 'اسپانیا',
    'FI': 'فنلاند',
    'FR': 'فرانسه',
    'GB': 'بریتانیا',
    'GE': 'گرجستان',
    'GR': 'یونان',
    'GT': 'گواتمالا',
    'HK': 'هنگ‌کنگ',
    'HR': 'کرواسی',
    'HU': 'مجارستان',
    'ID': 'اندونزی',
    'IE': 'ایرلند',
    'IL': 'اسرائیل',
    'IN': 'هند',
    'IQ': 'عراق',
    'IR': 'ایران',
    'IS': 'ایسلند',
    'IT': 'ایتالیا',
    'JO': 'اردن',
    'JP': 'ژاپن',
    'KE': 'کنیا',
    'KG': 'قرقیزستان',
    'KH': 'کامبوج',
    'KR': 'کره جنوبی',
    'KW': 'کویت',
    'KZ': 'قزاقستان',
    'LB': 'لبنان',
    'LI': 'لیختن‌اشتاین',
    'LK': 'سری‌لانکا',
    'LT': 'لیتوانی',
    'LU': 'لوکزامبورگ',
    'LV': 'لتونی',
    'MA': 'مراکش',
    'MD': 'مولداوی',
    'ME': 'مونته‌نگرو',
    'MK': 'مقدونیه شمالی',
    'MN': 'مغولستان',
    'MO': 'ماکائو',
    'MT': 'مالت',
    'MX': 'مکزیک',
    'MY': 'مالزی',
    'NG': 'نیجریه',
    'NL': 'هلند',
    'NO': 'نروژ',
    'NP': 'نپال',
    'NZ': 'نیوزیلند',
    'OM': 'عمان',
    'PA': 'پاناما',
    'PE': 'پرو',
    'PH': 'فیلیپین',
    'PK': 'پاکستان',
    'PL': 'لهستان',
    'PR': 'پورتوریکو',
    'PT': 'پرتغال',
    'PY': 'پاراگوئه',
    'QA': 'قطر',
    'RO': 'رومانی',
    'RS': 'صربستان',
    'RU': 'روسیه',
    'SA': 'عربستان',
    'SC': 'سیشل',
    'SE': 'سوئد',
    'SG': 'سنگاپور',
    'SI': 'اسلوونی',
    'SK': 'اسلواکی',
    'TH': 'تایلند',
    'TJ': 'تاجیکستان',
    'TM': 'ترکمنستان',
    'TN': 'تونس',
    'TR': 'ترکیه',
    'TW': 'تایوان',
    'UA': 'اوکراین',
    'US': 'آمریکا',
    'UY': 'اروگوئه',
    'UZ': 'ازبکستان',
    'VE': 'ونزوئلا',
    'VG': 'جزایر ویرجین بریتانیا',
    'VN': 'ویتنام',
    'XK': 'کوزوو',
    'ZA': 'آفریقای جنوبی',
  };

  static const Map<String, String> _names = {
    'AD': 'Andorra',
    'AE': 'United Arab Emirates',
    'AF': 'Afghanistan',
    'AL': 'Albania',
    'AM': 'Armenia',
    'AR': 'Argentina',
    'AT': 'Austria',
    'AU': 'Australia',
    'AZ': 'Azerbaijan',
    'BA': 'Bosnia and Herzegovina',
    'BD': 'Bangladesh',
    'BE': 'Belgium',
    'BG': 'Bulgaria',
    'BH': 'Bahrain',
    'BO': 'Bolivia',
    'BR': 'Brazil',
    'BY': 'Belarus',
    'BZ': 'Belize',
    'CA': 'Canada',
    'CH': 'Switzerland',
    'CL': 'Chile',
    'CN': 'China',
    'CO': 'Colombia',
    'CR': 'Costa Rica',
    'CW': 'Curacao',
    'CY': 'Cyprus',
    'CZ': 'Czechia',
    'DE': 'Germany',
    'DK': 'Denmark',
    'DO': 'Dominican Republic',
    'DZ': 'Algeria',
    'EC': 'Ecuador',
    'EE': 'Estonia',
    'EG': 'Egypt',
    'ES': 'Spain',
    'FI': 'Finland',
    'FR': 'France',
    'GB': 'United Kingdom',
    'GE': 'Georgia',
    'GR': 'Greece',
    'GT': 'Guatemala',
    'HK': 'Hong Kong',
    'HR': 'Croatia',
    'HU': 'Hungary',
    'ID': 'Indonesia',
    'IE': 'Ireland',
    'IL': 'Israel',
    'IN': 'India',
    'IQ': 'Iraq',
    'IR': 'Iran',
    'IS': 'Iceland',
    'IT': 'Italy',
    'JO': 'Jordan',
    'JP': 'Japan',
    'KE': 'Kenya',
    'KG': 'Kyrgyzstan',
    'KH': 'Cambodia',
    'KR': 'South Korea',
    'KW': 'Kuwait',
    'KZ': 'Kazakhstan',
    'LB': 'Lebanon',
    'LI': 'Liechtenstein',
    'LK': 'Sri Lanka',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'LV': 'Latvia',
    'MA': 'Morocco',
    'MD': 'Moldova',
    'ME': 'Montenegro',
    'MK': 'North Macedonia',
    'MN': 'Mongolia',
    'MO': 'Macau',
    'MT': 'Malta',
    'MX': 'Mexico',
    'MY': 'Malaysia',
    'NG': 'Nigeria',
    'NL': 'Netherlands',
    'NO': 'Norway',
    'NP': 'Nepal',
    'NZ': 'New Zealand',
    'OM': 'Oman',
    'PA': 'Panama',
    'PE': 'Peru',
    'PH': 'Philippines',
    'PK': 'Pakistan',
    'PL': 'Poland',
    'PR': 'Puerto Rico',
    'PT': 'Portugal',
    'PY': 'Paraguay',
    'QA': 'Qatar',
    'RO': 'Romania',
    'RS': 'Serbia',
    'RU': 'Russia',
    'SA': 'Saudi Arabia',
    'SC': 'Seychelles',
    'SE': 'Sweden',
    'SG': 'Singapore',
    'SI': 'Slovenia',
    'SK': 'Slovakia',
    'TH': 'Thailand',
    'TJ': 'Tajikistan',
    'TM': 'Turkmenistan',
    'TN': 'Tunisia',
    'TR': 'Turkey',
    'TW': 'Taiwan',
    'UA': 'Ukraine',
    'US': 'United States',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VE': 'Venezuela',
    'VG': 'British Virgin Islands',
    'VN': 'Vietnam',
    'XK': 'Kosovo',
    'ZA': 'South Africa',
  };
}
